version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install awscli

  pre_build:
    commands:
      - echo "Preparing environment"
      - mkdir -p myprontuariobucket
      - echo "Sample content" > myprontuariobucket/sample.txt

  build:
    commands:
      - echo "Uploading to S3"
      - aws s3 cp myprontuariobucket/ s3://myprontuariobucket/results/ --recursive

artifacts:
  files:
    - '**/*'
